"""Contact form

Revision ID: c48537ef50a1
Revises: 8c1b7a6f6d89
Create Date: 2025-02-28 10:18:10.450527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48537ef50a1'
down_revision = '8c1b7a6f6d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('ContactID', sa.Integer(), nullable=False),
    sa.Column('ContactName', sa.String(length=40), nullable=False),
    sa.Column('ContactMail', sa.String(length=40), nullable=True),
    sa.Column('ContactTelefon', sa.String(length=30), nullable=True),
    sa.Column('ContactÄrende', sa.String(length=40), nullable=False),
    sa.Column('ContactMsg', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('ContactID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
